# Server
server.port                       = 8084

# Datasource
spring.datasource.url             = jdbc:h2:mem:smartdoc
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.username        = user
spring.datasource.password        = password
spring.jpa.database-platform      = org.hibernate.dialect.H2Dialect
spring.flyway.enabled             = false
spring.jpa.show-sql               = false
spring.jpa.hibernate.ddl-auto     = update

# Uploads
uploads.paths.base-dir                = /tmp/smartdoc-test/uploads
uploads.paths.videos                  = videos
uploads.paths.images                  = images
uploads.paths.documents               = documents
uploads.storage.max-items             = 1000
