# Spring profile: docker

spring.flyway.enabled  = true


spring.datasource.url  = jdbc:mysql://${MYSQL_HOST:mariadb}:${MYSQL_PORT:3306}/${DB_NAME:smartdoc}?createDatabaseIfNotExist=true

uploads.paths.base-dir = /opt/smartdoc/uploads
