# Server
server.port                       = 8084

# Datasource
spring.datasource.url             = jdbc:h2:mem:smartdoc
spring.datasource.driverClassName = org.h2.Driver
spring.datasource.username        = user
spring.datasource.password        = password
spring.jpa.database-platform      = org.hibernate.dialect.H2Dialect
spring.flyway.enabled             = false
spring.jpa.show-sql               = false
