openapi: 3.1.0
info:
  title: SmartDoc Document Management API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  description: >-
    API for managing person-related documents stored in a file system, and for
    serving SmartDoc UI plugin resources. Designed to be accessed via the OH-API
    proxy in integrated mode.
  version: 1.1.0
servers:
  - url: http://localhost:8080/api
tags:
  - name: Documents
    description: Operations related to document upload, retrieval, and deletion.
  - name: Persons
    description: Operations related to person identification.
  - name: System
    description: General system information and metadata.
paths:
  /documents:
    $ref: paths/documents.yaml
  /documents/{id}:
    $ref: paths/documents_{id}.yaml
  /persons:
    $ref: paths/persons.yaml
  /persons/{id}:
    $ref: paths/persons_{id}.yaml
  /persons/{id}/documents:
    $ref: paths/persons_{id}_documents.yaml
  /persons/{id}/restore:
    $ref: paths/persons_{id}_restore.yaml
  /document-types:
    $ref: paths/document-types.yaml
  /document-types/{id}:
    $ref: paths/document-types_{id}.yaml
  /document-types/{id}/restore:
    $ref: paths/document-types_{id}_restore.yaml
  /actuator/health:
    $ref: paths/health.yaml
components:
  securitySchemes:
    Basic:
      $ref: ./components/security/Basic.yaml
    Bearer:
      $ref: ./components/security/Bearer.yaml
security:
  - Bearer: [ ]
